# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=6)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('yanzheng_code', models.CharField(default=None, max_length=200)),
                ('isActiave', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户',
                'ordering': ['-c_time'],
                'verbose_name_plural': '用户',
            },
        ),
    ]
